apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend-service
spec:
  type: LoadBalancer  # Using LoadBalancer to expose the service externally
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: quiz-frontend
